name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: update sources.list
      run:  sudo apt update

    - name: install tools
      run: sudo apt-get -y install devscripts equivs
      
    - name: clone pve-qemu
      run: git clone git://git.proxmox.com/git/pve-qemu.git
          
    - name: install deps    
      run: cd pve-qemu && yes| sudo mk-build-deps --install
        
    - name: run make
      run: make deb
        
